/*


 FreeSand is a pure java implementation of a cellular automata
 simulation inspired by falling sand like games.

 Copyright (C) 2007 Robert B. Harris (freesand@trebor.org)
 Ported to JavaScript by Zhuowei
 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 02110-1301, USA.

*/
var d=true,f=false,l=new function(){this.d=function(c){return parseInt(Math.random()*c)};this.F=function(){return Math.random()>=0.5}},aa=5,ba=42;function p(c,e,t){this.G=c;this.D=e;this.C=t;this.value=c*65536+e*256+t;this.toString=function(){return"rgb("+c+","+e+","+t+")"}}function Element(c,e){this.b=c;this.color=e;this.value=this.color.value}
var q={e:new Element("Air",new p(0,0,0)),A:new Element("Water",new p(0,0,255)),f:new Element("Sand",new p(255,225,0)),j:new Element("Earth",new p(200,40,37)),r:new Element("Oil",new p(200,100,0)),t:new Element("Plant",new p(0,255,0)),u:new Element("Rock",new p(100,100,100)),h:new Element("Concrete",new p(150,150,150)),v:new Element("Salt",new p(200,200,200)),w:new Element("Saltwater",new p(50,150,200)),k:new Element("Fire",new p(204,0,0)),l:new Element("Fire2",new p(255,204,51)),m:new Element("Fire3",
new p(255,204,0)),n:new Element("Fire4",new p(255,153,0)),o:new Element("Fire5",new p(255,102,0)),p:new Element("Fire6",new p(255,51,0)),g:new Element("Black Hole",new p(128,0,64)),B:new Element("Water Source",new p(0,0,150)),z:new Element("Sand Source",new p(200,150,0)),q:new Element("Fire Source",new p(150,0,0)),s:new Element("Oil Source",new p(150,50,0))},r=q.e.value,s=q.A.value,B=q.f.value,G=q.j.value,H=q.r.value,I=q.t.value,J=q.u.value,M=q.k.value,ca=q.l.value,N=q.m.value,da=q.n.value,ea=q.o.value,
fa=q.p.value,ga=q.g.value,ha=q.B.value,ia=q.z.value,ja=q.q.value,ka=q.s.value,la=q.h.value,R=q.v.value,ma=q.w.value;
function na(c,e,t){this.width=c;this.height=e;this.a=Array(c*e);for(var C=0;C<this.a.length;C++)this.a[C]=t;this.background=q.e;this.c=Array(200);for(C=0;C<this.c.length;C++){this.c[C]=Array(this.width);for(t=0;t<this.c[C].length;t++)this.c[C][t]=parseInt(Math.random()*this.c[C].length)}this.i=function(D,O,n,o){D=parseInt(D-n/2);O=parseInt(O-n/2);o=o.value;for(var P=O;P<=O+n;P++)for(var Q=D;Q<=D+n;Q++)this.a[P*this.width+Q]=o};this.update=function(){for(var D=this.height-1;D>=0;--D){var O=D*this.width,
n=D==0,o=D==e-1,P=parseInt(Math.random()*200),Q;for(Q in this.c[P]){var z=this.c[P][Q],b=parseInt(O)+parseInt(z),g=this.a[b];if(!(g==r||g==J||g==G)){var j=z==0,k=z==this.width-1,h=b-this.width,i=b+this.width,u=i-1,K=i+1,v=b-1,w=b+1,S=n?J:this.a[h],T=o?J:this.a[i],E=o||j?J:this.a[u],F=o||k?J:this.a[K],x=j?J:this.a[v],y=k?J:this.a[w];if(g==M||g==ca||g==N||g==da||g==ea||g==fa){var a=[j?b:v,k?b:w,n?b:h,o?b:i],$;for($ in a){var A=this.a[a[$]];if((A==I||A==H)&&parseInt(Math.random()*3)==0)this.a[a[$]]=
M;else if(A==s){this.a[a[$]]=r;g=this.a[b]=r;break}}if(g==M){this.a[b]=N;continue}if(g==ca){this.a[b]=N;continue}if(g==N){this.a[b]=da;continue}if(g==da){this.a[b]=ea;continue}if(g==ea){this.a[b]=fa;continue}if(g==fa){this.a[b]=r;continue}}if(g==la){a=[j?b:v,k?b:w,o?b:i];for(var m in a)if(this.a[a[m]]==J&&parseInt(Math.random()*ba)==0)this.a[b]=J}if(g==ga){a=[j?b:v,k?b:w,n?b:h,o?b:i];for(m in a)this.a[a[m]]=r}else if(g==ha){a=[j?b:v,k?b:w,n?b:h,o?b:i];for(m in a)if(this.a[a[m]]==r&&l.d(10)==0)this.a[a[m]]=
s}else if(g==ka){a=[k?b:w,j?b:v,n?b:h,o?b:i];for(m in a)if(this.a[a[m]]==r)this.a[a[m]]=H}else if(g==ia){a=[j?b:v,k?b:w,n?b:h,o?b:i];for(m in a)if(this.a[a[m]]==r&&l.d(10)==0)this.a[a[m]]=B}else if(g==I){A=h-1;var L=h+1;a=[j?b:v,j||n?b:A,k?b:w,k||n?b:L,n?b:h,o?b:i,o||j?b:u,o||k?b:K];for(var za in a)if(this.a[a[za]]==r)for(m in a)if(this.a[a[m]]==s&&l.d(23)==0)this.a[a[m]]=I}else if(g==ja){a=[j?b:v,k?b:w,n?b:h,o?b:i];for(m in a)if(this.a[a[m]]==I||this.a[a[m]]==H)this.a[a[m]]=M}else{if(g==R){a=[j?
b:v,k?b:w,n?b:h,o?b:i];for(m in a)if(this.a[a[m]]==s&&l.d(aa)==0)this.a[b]=ma}a=-1;if(g==H){A=h-1;L=h+1;j=n||j?J:this.a[A];k=n||k?J:this.a[L];if(S==G||S==B)a=h;else if((j==G||j==B)&&(k==G||k==B))a=Math.random()>=0.5?A:L;else if(T==r)a=i;else if(E==r&&F==r)a=Math.random()>=0.5?u:K;else if(E==r)a=u;else if(F==r)a=K;else if((x==r||x==G||x==B)&&(y==r||y==G||y==B))a=Math.random()>=0.5?v:w;else if(x==r||x==G||x==B)a=v;else if(y==r||y==G||y==B)a=w;else{h=b-2;i=b+2;u=z<2?J:this.a[h];z=z>c-3?J:this.a[i];if(u==
r&&z==r)a=Math.random()>=0.5?i:h;else if(z==r)a=i;else if(u==r)a=h}}else if(g==s||g==ma){A=h-1;L=h+1;j=n||j?J:this.a[A];k=n||k?J:this.a[L];if(S==G||S==B||S==R)a=h;else if((j==G||j==B||j==R)&&(k==G||k==B||k==R))a=Math.random()>=0.5?A:L;else if(T==r||T==H)a=i;else if((E==r||E==H)&&(F==r||F==H))a=Math.random()>=0.5?u:K;else if(E==r||E==H)a=u;else if(F==r||F==H)a=K;else if((x==r||x==G||x==B||x==R)&&(y==r||y==G||y==B||y==R))a=Math.random()>=0.5?v:w;else if(x==r||x==G||x==B||x==R)a=v;else if(y==r||y==G||
y==B||y==R)a=w;else{h=b-2;i=b+2;u=z<2?J:this.a[h];z=z>c-3?J:this.a[i];if(u==r&&z==r)a=Math.random()>=0.5?i:h;else if(z==r)a=i;else if(u==r)a=h}}else if(T==r||T==s)a=i;else if((E==r||E==s)&&(F==r||F==s))a=Math.random()>=0.5?u:K;else if(E==r||E==s)a=u;else if(F==r||F==s)a=K;if(a!=-1){this.a[b]=this.a[a];this.a[a]=g}}}}}}};var U,V,W,X,Y=d,oa,pa=10,Z=f,qa=q.f,ra=15,sa=f,ta,ua=2;function va(){if(Y){U.update();wa();window.setTimeout(va,pa)}}function xa(){if(Z){Y=d;Z=f;va();document.getElementById("pause").innerHTML="Pause"}else{Y=f;Z=d;document.getElementById("pause").innerHTML="Resume"}}function wa(){var c,e,t;for(e=0;e<U.a.length;e++)if(oa[e]!=U.a[e]){t=e*4;c=U.a[e];X.data[t+2]=c%256;X.data[t+1]=(c%65536-c%256)/256;X.data[t]=(c-c%65536)/65536;oa[e]=U.a[e]}W.putImageData(X,0,0)}function ya(c){sa=d;Aa(c)}
function Ba(){sa=f}function Aa(c){if(sa){var e;if(c.pageX!=undefined&&c.pageY!=undefined){e=c.pageX;c=c.pageY}else{e=c.clientX+document.body.scrollLeft+document.documentElement.scrollLeft;c=c.clientY+document.body.scrollTop+document.documentElement.scrollTop}e-=V.offsetLeft;c-=V.offsetTop;U.i(parseInt(e/ua),parseInt(c/ua),ra,qa);Z&&wa()}}function Ca(){var c=parseInt(document.getElementById("timeinterval").value);if(c>10){pa=c;Y=f;Y=Z=d;Z=f;va()}}function Da(){ra=parseInt(ta.value);Ea(ra)}
window.onload=function(){V=document.getElementById("maincanvas");W=V.getContext("2d");V.style.width=V.width*ua+"px";V.style.height=V.height*ua+"px";X=W.getImageData(0,0,V.width,V.height);U=new na(V.width,V.height,r);document.getElementById("pause").onclick=xa;document.getElementById("loadbutton").onclick=Fa;document.getElementById("savebutton").onclick=Ga;ta=document.getElementById("pensizepicker");ta.onchange=Da;oa=Array(U.a.length);W.fillStyle="black";W.fillRect(0,0,V.width,V.height);for(var c=
3;c<X.data.length-3;c+=4)X.data[c]=255;V.onmousedown=ya;V.onmouseup=Ba;V.onmousemove=Aa;elementSel=document.getElementById("elementsel");c="";for(var e in q)if(q[e].b!="Fire1"&&q[e].b!="Fire2"&&q[e].b!="Fire3"&&q[e].b!="Fire4"&&q[e].b!="Fire5"&&q[e].b!="Fire6")c=c+'<button style="background-color: '+q[e].color.toString()+'" onclick="elementSelChange(\''+e+"')\">"+q[e].b+"</button>";elementSel.innerHTML=c;document.getElementById("intervalboxsubmit").onclick=Ca;va()};
window.elementSelChange=function(c){Ea(c);qa=q[c]};function Fa(){var c;if(localStorage&&localStorage.freesand_save1){U.a=localStorage.freesand_save1.split(",");c=d}else c=f;c||alert("There is no saved world. Click on the Save button to save the current world.")}function Ga(){Ea("saving to slot1");localStorage.freesand_save1=U.a.join()};function Ea(c){if(typeof console!="undefined")console.log(c);else typeof air!="undefined"&&air.H(c)};
